# @user-gated
"""Build the kanban-harness agent patches from pristine upstream files.

    python3 scripts/harness-patches/build.py <upstream dir> <out dir>

<upstream dir> holds upstream's hermes_cli/kanban_db.py, tools/kanban_tools.py and
agent/chat_completion_helpers.py (e.g. `git show <commit>:<path>` from a
hermes-agent checkout). The output is whole-file replacements for the install
(docs/patches.md):

* hermes_cli/kanban_db.py  -- terminal-writes: on a board with a deployed spec,
  complete_task refuses for every caller and archive_task archives only from a
  status the table archives from.
* tools/kanban_tools.py    -- fail-closed: every kanban tool that can write
  refuses while the kanban-harness plugin has not registered. And visible-wait:
  while a request has received nothing, the card's heartbeat is left alone, the
  claim is extended, and one note on the card says who is being waited on.
* agent/chat_completion_helpers.py -- visible-wait: the streaming wait loop
  reports begin / tick / silence / bytes to that note, and a silent request
  ends at stream_silence_limit_s (default 300s) instead of never.

The patches are generated, not kept: anyone can rebuild them from upstream and
diff. The build refuses an upstream file whose hash is not the pinned one (a
silent rebuild against a newer upstream is the regression the pin exists to
catch), and the output is deterministic: same upstream, same bytes.

Contract: docs/harness-contract.md (T33). Only the user changes this file.
"""
import hashlib
import re
import sys
from pathlib import Path

#: upstream NousResearch/hermes-agent b88d0007c. Moving a pin is a review:
#: read what changed upstream, then re-derive the patch.
PINNED = {
    "hermes_cli/kanban_db.py":
        "9ebdaee7d03995754a9409fd4cc42b3560f05816a9b69341a2e5e8a69d05436d",
    "tools/kanban_tools.py":
        "39b5d75b0ef1790949724560847e6b64803c8dd488433fee4d5971dd300fd973",
    "agent/chat_completion_helpers.py":
        "002e78d009a0e758dd724b732b2402b7e4740de40d1da642f214e85327201de3",
}
MARKERS = {
    "hermes_cli/kanban_db.py": "kanban-harness-patch: terminal-writes",
    "tools/kanban_tools.py": "kanban-harness-patch: fail-closed",
    "agent/chat_completion_helpers.py": "kanban-harness-patch: visible-wait",
}
READ_ONLY = {"kanban_show", "kanban_list"}

HEADER = """# @user-gated
# {marker}
# upstream-sha256: {sha}
# Generated by hermes-workflows scripts/harness-patches/build.py from upstream
# {rel} with the hash above. Do not edit: rebuild. Contract:
# hermes-workflows docs/harness-contract.md. Only the user changes this file.
"""

GATE_A = r'''

# ---------------------------------------------------------------------------
# kanban-harness-patch: terminal-writes
#
# This gate guards against AGENTS inside the runtime, not the user. On a
# board with a deployed specification (board.yaml) there is ONE door to done
# for an agent -- the user's accept (hermes-workflows board_cli), which
# writes its own SQL -- so complete_task refuses every agent caller: the
# kanban tool, `hermes kanban complete`, a swarm root, an agent hitting the
# dashboard API directly. archive_task refuses an agent moving a card from a
# status the table does not archive from.
#
# The user moves cards as they please -- at a terminal, or through Hermes's
# own web dashboard -- and neither is gated here: a user's move that is not
# an accept is not blocked, it is recorded (the escalator pages it; T21/T22).
# So the gate first asks who is calling, not what the board says:
#
#   _is_agent_caller() -- agent iff any of: HERMES_KANBAN_TASK is set (a
#   worker's own card), HERMES_PROFILE is set (a role name), or HERMES_HOME
#   is set and does not resolve to ~/.hermes (a profile's own sandboxed
#   home). Nothing else. Not an agent -> this function returns immediately
#   and the call runs upstream, unmodified.
#
# Deliberately NOT identity by TTY or process ancestry, the way board_cli's
# own accept/rework/reopen still check (that strict check is unchanged,
# elsewhere): the web dashboard server has no TTY at all -- it's a long-lived
# background process -- and it IS a Hermes process, so an ancestor check
# would see it exactly as it sees a worker. Those checks answer "is this a
# real terminal spawned outside Hermes"; this gate answers a narrower
# question -- "is this call carrying an in-runtime agent identity" -- and the
# three env vars above are that identity, set only inside the runtime.
#
# For an agent caller, a specification that is deployed but missing,
# unreadable or unparseable refuses both. That is not a bug when it one day
# blocks a legitimate move during a bad edit: the alternative is that a
# corrupted table is an open door, which is exactly how the first escape
# happened.
# A board with no specification deployed runs upstream unchanged.
# ---------------------------------------------------------------------------

class TerminalWriteRefused(RuntimeError):
    """A write to done or archived that the board's table does not allow."""


def _is_agent_caller() -> bool:
    """True iff this call carries an in-runtime agent identity. See the gate
    comment above for why this -- not a TTY or ancestry check -- is right
    here: it is the user's own move (terminal or web dashboard) that must go
    through, and the user's process is indistinguishable from the harness's
    other long-lived processes by TTY or parentage alone."""
    if os.environ.get("HERMES_KANBAN_TASK", "").strip():
        return True
    if os.environ.get("HERMES_PROFILE", "").strip():
        return True
    home = os.environ.get("HERMES_HOME", "").strip()
    if home:
        resolved = Path(os.path.expanduser(home)).resolve(strict=False)
        live = Path(os.path.expanduser("~/.hermes")).resolve(strict=False)
        if resolved != live:
            return True
    return False


def _deployed_board_spec() -> Optional[Path]:
    env = os.environ.get("KANBAN_BOARD_FILE", "").strip()
    if env:
        return Path(os.path.expanduser(env))
    home = os.environ.get("HERMES_HOME", "").strip() or "~/.hermes"
    live = Path(os.path.expanduser(home)) / "board.yaml"
    return live if live.exists() else None


def _archivable_statuses(path: Path) -> set:
    """The statuses the table lets a card be archived from. Raises when the
    specification cannot be read as a table."""
    import yaml
    doc = yaml.safe_load(path.read_text())
    board = doc.get("board", doc) if isinstance(doc, dict) else None
    columns = board.get("columns") if isinstance(board, dict) else None
    moves = board.get("moves") if isinstance(board, dict) else None
    if not isinstance(columns, dict) or not columns or not isinstance(moves, list) or not moves:
        raise ValueError("no columns or no moves")
    status = {name: str((c or {}).get("status", name)) for name, c in columns.items()}
    return {status[m["from"]] for m in moves
            if isinstance(m, dict) and m.get("from") in status
            and status.get(m.get("to")) == "archived"}


def _refuse_terminal_write(fn: str, task_id: str, why: str) -> None:
    msg = (f"[kanban-harness] {fn} refused for {task_id}: {why} This refusal is "
           "final. The board did not move.")
    try:
        log = Path(os.path.expanduser("~/.hermes/logs/kanban-harness.log"))
        log.parent.mkdir(parents=True, exist_ok=True)
        with open(log, "a", encoding="utf-8") as fh:
            fh.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] [BLOCKED] board=- "
                     f"profile={os.environ.get('HERMES_PROFILE') or '-'} "
                     f"tool={fn} {msg}\n")
    except OSError:
        pass
    raise TerminalWriteRefused(msg)


def _protocol_violation_text() -> str:
    """What the runtime tells a worker that exited without a sanctioned exit.
    On a board with a deployed spec, kanban_complete is refused to every agent,
    so naming it would send the worker into a refusal: name the hand-off."""
    if _deployed_board_spec() is not None:
        return ("worker exited cleanly (rc=0) without calling kanban_handoff, the "
                "only exit this board allows an agent -- protocol violation")
    return ("worker exited cleanly (rc=0) without calling "
            "kanban_complete or kanban_block — protocol violation")


def _terminal_write_gate(fn: str, conn: sqlite3.Connection, task_id: str) -> None:
    if not _is_agent_caller():
        return
    spec = _deployed_board_spec()
    if spec is None:
        return
    try:
        archivable = _archivable_statuses(spec)
    except Exception as exc:
        _refuse_terminal_write(fn, task_id, f"the board specification {spec} is deployed "
                               f"but cannot be read as a table ({exc}); nothing moves "
                               "until it is fixed.")
    if fn == "complete_task":
        _refuse_terminal_write(fn, task_id, "on this board the only way to done is the "
                               "user's accept: python3 scripts/resilience/board_cli.py "
                               f"accept {task_id}.")
    row = conn.execute("SELECT status FROM tasks WHERE id = ?", (task_id,)).fetchone()
    if row is not None and row[0] not in archivable:
        _refuse_terminal_write(fn, task_id, f"the table does not archive a card from "
                               f"{row[0]!r} (only from {sorted(archivable)}).")

'''

GATE_B = r'''

# ---------------------------------------------------------------------------
# kanban-harness-patch: fail-closed
#
# Every kanban tool that can write refuses while the kanban-harness plugin
# has not registered its pre_tool_call hook in this process. Only kanban_show
# and kanban_list stay available: a read cannot move anything, and a worker
# that cannot read its card cannot write a sensible hand-off.
# heartbeat is refused too, deliberately: a worker whose harness never loaded
# cannot heartbeat, so it is seen as stalled and reclaimed instead of running
# unguarded. That is the intended outcome, not an oversight.
# ---------------------------------------------------------------------------

def _kanban_harness_loaded() -> bool:
    try:
        from hermes_cli.plugins import get_plugin_manager
        hooks = get_plugin_manager()._hooks.get("pre_tool_call", [])
    except Exception:
        return False
    for cb in hooks:
        code = getattr(cb, "__code__", None)
        path = (getattr(code, "co_filename", "") or "").replace("\\", "/")
        if path.endswith("/kanban-harness/__init__.py"):
            return True
    return False


def _harness_guard(name, handler):
    def guarded(args, **kw):
        if _kanban_harness_loaded():
            return handler(args, **kw)
        msg = (f"[kanban-harness] {name} refused: kanban-harness is not loaded in this "
               "process, and no kanban write runs without it. This refusal is final. "
               "The board did not move.")
        try:
            from pathlib import Path
            import time
            log = Path(os.path.expanduser("~/.hermes/logs/kanban-harness.log"))
            log.parent.mkdir(parents=True, exist_ok=True)
            with open(log, "a", encoding="utf-8") as fh:
                fh.write(f"[{time.strftime('%Y-%m-%d %H:%M:%S')}] [BLOCKED] board=- "
                         f"profile={os.environ.get('HERMES_PROFILE') or '-'} "
                         f"tool={name} {msg}\n")
        except OSError:
            pass
        return tool_error(msg)
    guarded.__wrapped__ = handler
    return guarded

'''

WAIT_B = r'''

# ---------------------------------------------------------------------------
# kanban-harness-patch: visible-wait
#
# A heartbeat means progress, not existence. While a model request has
# received nothing, the worker is WAITING, and the card says so:
#
# * the card's last_heartbeat_at is left alone -- only bytes (a chunk, a
#   stream event) or work between requests refresh it;
# * the claim is still extended every tick, so the dispatcher does not
#   reclaim a live worker that is waiting: a wait is a queue, never a failure,
#   and it never costs the card its retry budget;
# * one comment on the card, written once the wait passes
#   VISIBLE_WAIT_NOTE_AFTER seconds and updated in place on every tick, names
#   the endpoint, the model, the attempt and how long. The first bytes close it.
#
# The marker line under the sentence is what the escalator reads to page one
# "backend not serving" per endpoint and model. The sentence is for people.
# agent/chat_completion_helpers.py (same patch) calls these from its wait loop.
# ---------------------------------------------------------------------------

import threading as _vw_threading
import time as _vw_time

VISIBLE_WAIT_NOTE_AFTER = 30
VISIBLE_WAIT_AUTHOR = "visible-wait"
_VISIBLE_WAIT_LOCK = _vw_threading.RLock()
_VISIBLE_WAIT = {"pending": False, "since": 0.0, "attempts": 0, "max": 0,
                 "endpoint": "?", "model": "?", "note": None, "silent": 0.0,
                 "ended": None}


def _vw_duration(seconds) -> str:
    s = int(max(0, seconds))
    if s < 60:
        return f"{s}s"
    m = s // 60
    return f"{m}m" if m < 60 else f"{m // 60}h{m % 60:02d}m"


def _vw_body(state: str) -> str:
    w = _VISIBLE_WAIT
    who = f"{w['endpoint']} (model {w['model']})"
    of = f" of {w['max']}" if w["max"] else ""
    if state == "closed":
        text = (f"Waited {_vw_duration(_vw_time.time() - w['since'])} on the model backend "
                f"{who} over {w['attempts']} attempt(s); the backend answered at "
                f"{_vw_time.strftime('%H:%M')} and work resumed. The wait cost the card "
                "nothing.")
    else:
        text = (f"Waiting on the model backend: {who} has sent nothing for "
                f"{_vw_duration(w['silent'])} (attempt {w['attempts']}{of}). This is a "
                "wait, not a failure: the worker keeps retrying in place and the card's "
                "retry budget is untouched.")
        if w["ended"]:
            text += (f" It ended one request after {_vw_duration(w['ended'][0])} of "
                     f"silence (stream_silence_limit_s={int(w['ended'][1])}) and retries "
                     "in place.")
    return (f"{text}\n[visible-wait {state} endpoint={w['endpoint']} model={w['model']} "
            f"since={int(w['since'])} updated={int(_vw_time.time())}]")


def _vw_write(state: str) -> None:
    tid = os.environ.get("HERMES_KANBAN_TASK")
    if not tid:
        return
    try:
        kb, conn = _connect()
        try:
            body = _vw_body(state)
            if _VISIBLE_WAIT["note"] is None:
                _VISIBLE_WAIT["note"] = kb.add_comment(conn, tid, VISIBLE_WAIT_AUTHOR, body)
            else:
                with kb.write_txn(conn):
                    conn.execute("UPDATE task_comments SET body = ? WHERE id = ? AND "
                                 "task_id = ?", (body, _VISIBLE_WAIT["note"], tid))
        finally:
            conn.close()
    except Exception:
        logger.debug("visible-wait: note failed", exc_info=True)


def _vw_extend_claim() -> None:
    tid = os.environ.get("HERMES_KANBAN_TASK")
    if not tid:
        return
    try:
        kb, conn = _connect()
        try:
            kb.heartbeat_claim(conn, tid, claimer=os.environ.get("HERMES_KANBAN_CLAIM_LOCK"))
        finally:
            conn.close()
    except Exception:
        logger.debug("visible-wait: claim extension failed", exc_info=True)


def visible_wait_pending() -> bool:
    return bool(_VISIBLE_WAIT["pending"])


def visible_wait_begin(endpoint, model, max_attempts) -> None:
    """A request starts. The first one after bytes opens a wait; each later
    one is the next attempt of the same wait."""
    with _VISIBLE_WAIT_LOCK:
        w = _VISIBLE_WAIT
        if not w["pending"]:
            w.update(pending=True, since=_vw_time.time(), attempts=0, note=None,
                     silent=0.0, ended=None)
        w.update(endpoint=str(endpoint or "?"), model=str(model or "?"),
                 max=int(max_attempts or 0))
        w["attempts"] += 1


def visible_wait_tick(silent_seconds) -> None:
    """The wait loop's timer fired with nothing received."""
    with _VISIBLE_WAIT_LOCK:
        w = _VISIBLE_WAIT
        if not w["pending"]:
            return
        w["silent"] = max(float(silent_seconds), _vw_time.time() - w["since"])
        _vw_extend_claim()
        if w["silent"] >= VISIBLE_WAIT_NOTE_AFTER:
            _vw_write("open")


def visible_wait_silence_ended(silent_seconds, limit) -> None:
    """A request hit the silence bound and was ended; the worker retries."""
    with _VISIBLE_WAIT_LOCK:
        w = _VISIBLE_WAIT
        if not w["pending"]:
            return
        w["ended"] = (float(silent_seconds), float(limit))
        w["silent"] = max(float(silent_seconds), _vw_time.time() - w["since"])
        _vw_write("open")


def visible_wait_progress() -> None:
    """Bytes arrived: close the note, and let the next touch refresh the card."""
    global _auto_heartbeat_last_attempt
    if not _VISIBLE_WAIT["pending"]:
        return
    with _VISIBLE_WAIT_LOCK:
        if not _VISIBLE_WAIT["pending"]:
            return
        if _VISIBLE_WAIT["note"] is not None:
            _vw_write("closed")
        _VISIBLE_WAIT.update(pending=False, note=None, ended=None)
        _auto_heartbeat_last_attempt = 0.0

'''

HELPERS_C = r'''

# ---------------------------------------------------------------------------
# kanban-harness-patch: visible-wait
#
# The streaming wait loop tells the card what it is waiting on
# (tools/kanban_tools.py, same patch): a request start opens a wait, the 30s
# timer records it, bytes close it. The timer still touches the agent's own
# activity (the gateway must not kill a waiting worker), but the card's
# heartbeat moves only on bytes.
#
# stream_silence_limit_s is a per-request silence bound, not a task timeout: a
# request that receives nothing for that long is ended, the reason goes on the
# card, and the worker's own retry loop tries again in place. Upstream holds a
# local endpoint's silent request forever; here every request is bounded.
# Set it with HERMES_STREAM_SILENCE_LIMIT_S or agent.stream_silence_limit_s in
# $HERMES_HOME/config.yaml. There is no value that means "unbounded": zero,
# negative, infinite or unreadable falls back to the default.
# ---------------------------------------------------------------------------

VISIBLE_WAIT_SILENCE_LIMIT_DEFAULT = 300.0


def _visible_wait_silence_limit() -> float:
    raw = os.environ.get("HERMES_STREAM_SILENCE_LIMIT_S", "").strip()
    if not raw:
        try:
            import yaml
            home = os.environ.get("HERMES_HOME") or os.path.expanduser("~/.hermes")
            with open(os.path.join(home, "config.yaml"), encoding="utf-8") as fh:
                cfg = yaml.safe_load(fh) or {}
            agent_cfg = cfg.get("agent") if isinstance(cfg, dict) else None
            value = agent_cfg.get("stream_silence_limit_s") if isinstance(agent_cfg, dict) else None
            raw = "" if value is None else str(value)
        except Exception:
            raw = ""
    if not raw:
        return VISIBLE_WAIT_SILENCE_LIMIT_DEFAULT
    try:
        value = float(raw)
    except ValueError:
        value = float("nan")
    if not 0 < value < float("inf"):
        logger.warning("stream_silence_limit_s=%r is not a positive finite number of "
                       "seconds; using %.0f", raw, VISIBLE_WAIT_SILENCE_LIMIT_DEFAULT)
        return VISIBLE_WAIT_SILENCE_LIMIT_DEFAULT
    return value


def _visible_wait_stale_bound(stale_timeout: float) -> float:
    """Upstream's stale timeout, never longer than the silence bound."""
    return min(float(stale_timeout), _visible_wait_silence_limit())


def _visible_wait(kind, agent, api_kwargs, *args) -> None:
    """Report the wait loop to the card. Never raises into the agent loop."""
    if not os.environ.get("HERMES_KANBAN_TASK"):
        return
    try:
        from tools import kanban_tools as _kt
        if kind == "begin":
            from urllib.parse import urlparse
            base = str(getattr(agent, "base_url", "") or "")
            endpoint = urlparse(base).netloc or base or "?"
            model = (api_kwargs or {}).get("model") or getattr(agent, "model", "") or "?"
            _kt.visible_wait_begin(endpoint, model, getattr(agent, "_api_max_retries", 0))
        elif kind == "tick":
            _kt.visible_wait_tick(*args)
        elif kind == "silence_ended":
            _kt.visible_wait_silence_ended(*args)
        elif kind == "progress":
            _kt.visible_wait_progress()
    except Exception:
        logger.debug("visible-wait: %s failed", kind, exc_info=True)

'''


class UpstreamMismatch(ValueError):
    """The upstream file is not the one the patch was derived from."""


def _patch_kanban_db(text):
    anchor = "\ndef complete_task(\n"
    assert text.count(anchor) == 1, "complete_task moved upstream"
    text = text.replace(anchor, GATE_A + anchor, 1)
    m = re.search(r"def complete_task\(.*?\n    \"\"\".*?\"\"\"\n", text, re.S)
    text = (text[:m.end()] + '    _terminal_write_gate("complete_task", conn, task_id)\n'
            + text[m.end():])
    old = "def archive_task(conn: sqlite3.Connection, task_id: str) -> bool:\n"
    assert text.count(old) == 1, "archive_task moved upstream"
    text = text.replace(old, old + '    _terminal_write_gate("archive_task", conn, task_id)\n', 1)
    msg = ('                error_text = (\n'
           '                    "worker exited cleanly (rc=0) without calling "\n'
           '                    "kanban_complete or kanban_block — protocol violation"\n'
           '                )\n')
    assert text.count(msg) == 1, "the protocol-violation message moved upstream"
    return text.replace(msg, "                error_text = _protocol_violation_text()\n", 1)


def _patch_kanban_tools(text):
    anchor = ("\n# ---------------------------------------------------------------------------"
              "\n# Registration\n")
    assert text.count(anchor) == 1, "the registration block moved upstream"
    text = text.replace(anchor, GATE_B + anchor, 1)

    def guard(m):
        block = m.group(0)
        name = re.search(r'name="([^"]+)"', block).group(1)
        if name in READ_ONLY:
            return block
        return re.sub(r"handler=(\w+),", rf'handler=_harness_guard("{name}", \1),',
                      block, count=1)

    text = re.sub(r"registry\.register\((?:.|\n)*?\n\)", guard, text)

    # visible-wait: the wait API, and the bridge leaves the card's heartbeat
    # alone while a request has received nothing (the claim is still extended).
    text = text.replace(anchor, WAIT_B + anchor, 1)
    beat = ("            try:\n"
            "                kb.heartbeat_worker(conn, tid, note=None, expected_run_id=run_id)\n"
            "            except Exception:\n"
            "                logger.debug(\"auto-heartbeat: heartbeat_worker failed\", exc_info=True)\n")
    assert text.count(beat) == 1, "the auto-heartbeat bridge moved upstream"
    return text.replace(beat, "            if not visible_wait_pending():\n"
                        + "".join("    " + l + "\n" for l in beat.splitlines()), 1)


def _replace_once(text, old, new, what):
    assert text.count(old) == 1, f"{what} moved upstream"
    return text.replace(old, new, 1)


def _patch_helpers(text):
    text = _replace_once(text, "\ndef _ra():\n", HELPERS_C + "\ndef _ra():\n", "_ra")
    # a request starts: open (or count) the wait
    text = _replace_once(
        text, '        agent._touch_activity("waiting for provider response (streaming)")\n',
        '        _visible_wait("begin", agent, api_kwargs)\n'
        '        agent._touch_activity("waiting for provider response (streaming)")\n',
        "the streaming request start")
    text = _replace_once(
        text, '        # Reset stale-stream timer for this attempt\n'
              '        last_chunk_time["t"] = time.time()\n',
        '        # Reset stale-stream timer for this attempt\n'
        '        last_chunk_time["t"] = time.time()\n'
        '        _visible_wait("begin", agent, api_kwargs)\n',
        "the anthropic request start")
    # bytes: close the wait before the touch that refreshes the card
    text, n = re.subn(r'\n( +)agent\._touch_activity\("receiving stream response"\)\n',
                      lambda m: (f'\n{m.group(1)}_visible_wait("progress", agent, api_kwargs)'
                                 f'\n{m.group(1)}agent._touch_activity("receiving stream '
                                 'response")\n'), text)
    assert n == 2, "the chunk sites moved upstream"
    # the 30s timer: a wait, recorded as one
    text = _replace_once(
        text, '                f"waiting for stream response ({_waiting_secs}s, no chunks yet)"\n'
              '            )\n',
        '                f"waiting for stream response ({_waiting_secs}s, no chunks yet)"\n'
        '            )\n'
        '            _visible_wait("tick", agent, api_kwargs, _waiting_secs)\n',
        "the wait-loop timer")
    # the silence bound: every request is bounded, local endpoints included
    text = _replace_once(
        text, '_stream_stale_timeout = float("inf")',
        '_stream_stale_timeout = _visible_wait_stale_bound(float("inf"))',
        "the local stale-timeout override")
    text = _replace_once(
        text, '    t = threading.Thread(target=_call, daemon=True)\n    t.start()\n'
              '    _last_heartbeat = time.time()\n',
        '    _stream_stale_timeout = _visible_wait_stale_bound(_stream_stale_timeout)\n'
        '    t = threading.Thread(target=_call, daemon=True)\n    t.start()\n'
        '    _last_heartbeat = time.time()\n',
        "the wait-loop start")
    return _replace_once(
        text, '            agent._buffer_status(\n'
              '                f"⚠️ No response from provider for {int(_stale_elapsed)}s "\n',
        '            _visible_wait("silence_ended", agent, api_kwargs, _stale_elapsed,\n'
        '                          _stream_stale_timeout)\n'
        '            agent._buffer_status(\n'
        '                f"⚠️ No response from provider for {int(_stale_elapsed)}s "\n',
        "the stale kill")


_PATCHERS = {"hermes_cli/kanban_db.py": _patch_kanban_db,
             "tools/kanban_tools.py": _patch_kanban_tools,
             "agent/chat_completion_helpers.py": _patch_helpers}


def build(upstream, out):
    """Write both patches into ``out``. Raises UpstreamMismatch on an unpinned file."""
    upstream, out = Path(upstream), Path(out)
    for rel, patch in _PATCHERS.items():
        raw = (upstream / rel).read_bytes()
        sha = hashlib.sha256(raw).hexdigest()
        if sha != PINNED[rel]:
            raise UpstreamMismatch(
                f"{rel}: upstream sha256 {sha} is not the pinned {PINNED[rel]}. Read what "
                "changed upstream, re-derive the patch, then move the pin.")
        target = out / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes((HEADER.format(marker=MARKERS[rel], sha=sha, rel=rel)
                            + patch(raw.decode())).encode())
    return out


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    try:
        print(f"built {build(sys.argv[1], sys.argv[2])}")
    except UpstreamMismatch as exc:
        sys.exit(f"refused: {exc}")
